language: python
sudo: true
dist: trusty


python:
  - "3.6"

install:
  - pip install -r test_requirements.txt
  - pip install codecov
  - pip install coverage

before_script:
  - python before_script.py

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - chalice deploy
