swagger: '2.0'
info:
  title: Hay Image S3 Wrapper
  version: 1.0.0
schemes:
  - https
  - http
produces:
  - application/json
paths:
  /img:
    post:
      summary: save image.
      tags:
        - IMG
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/HayImg'
      responses:
        '200':
          description: A success saving
          schema:
            $ref: '#/definitions/HayMsg'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    get:
      summary: get image.
      tags:
        - IMG
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/HayMsg'
      responses:
        '200':
          description: A success saving
          schema:
            $ref: '#/definitions/HayImg'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  HayImg:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Image'

  HayMsg:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  Image:
    type: object
    properties:
      id:
        type: string
      img:
        type: string
      timestamp:
        type: string
        format: datetime
      widht:
        type: integer
      height:
        type: integer

  Message:
    type: object
    properties:
      id:
        type: string
      msg:
        type: string
      timestamp:
        type: string
        format: datetime
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string